# Generated by Django 3.2.13 on 2022-05-25 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='show',
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(upload_to='uploads/avatars/profile/'),
        ),
    ]
