# Generated by Django 3.2.13 on 2022-05-03 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='show',
            field=models.BooleanField(default=True, verbose_name='Показать'),
        ),
    ]
