# Generated by Django 4.0.4 on 2022-05-06 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0002_auto_20220505_1857'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_icons', to='workshop.icon'),
        ),
    ]
