# Generated by Django 3.2.13 on 2022-05-02 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220502_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='text',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
