# Generated by Django 3.2.13 on 2022-05-02 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_auto_20220502_1214'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fields',
        ),
    ]
