# Generated by Django 3.2.13 on 2022-05-27 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.datetime_safe
import tinymce.models
import workshop.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('date_edit', models.DateField(default=django.utils.datetime_safe.date.today, verbose_name='Дата последнего редактирования')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Блок',
                'verbose_name_plural': 'Блоки',
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=1000, validators=[workshop.validators.OrReValidator(('[a-zA-Z0-9_]+@[a-zA-Z0-9_]+.[a-z0-9]+', '\\+?1?\\d{8,15}', 'https?://[a-zA-Z0-1\\.]+.[a-zA-Z0-1\\:\\.]+(/[a-zA-Z0-1]+)*/?'))], verbose_name='Номер телефона | Email | URL')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тэг',
                'verbose_name_plural': 'Тэги',
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', tinymce.models.HTMLField(verbose_name='Текст')),
                ('block', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='workshop.block')),
            ],
            options={
                'verbose_name': 'Текст',
                'verbose_name_plural': 'Текста',
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show', models.BooleanField(default=True, verbose_name='Показать')),
                ('date_edit', models.DateField(default=django.utils.datetime_safe.date.today, verbose_name='Дата последнего редактирования')),
                ('image', models.ImageField(blank=True, upload_to='uploads/avatars/resume/')),
                ('text', tinymce.models.HTMLField(verbose_name='Описание')),
                ('contacts', models.ManyToManyField(blank=True, to='workshop.Contact', verbose_name='Контакты')),
                ('tags', models.ManyToManyField(blank=True, to='workshop.Tag', verbose_name='Теги')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Резюме',
                'verbose_name_plural': 'Резюме',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show', models.BooleanField(default=True, verbose_name='Показать')),
                ('file', models.FileField(upload_to='uploads/files/%d_%m_%Y/')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop.block')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
            },
        ),
        migrations.AddField(
            model_name='block',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop.resume'),
        ),
    ]
