# Generated by Django 3.2.13 on 2022-05-05 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show', models.BooleanField(default=True, verbose_name='Показать')),
                ('icon', models.ImageField(null=True, upload_to='uploads/icons/', verbose_name='Иконка')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тэг',
                'verbose_name_plural': 'Тэги',
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show', models.BooleanField(default=True, verbose_name='Показать')),
                ('image', models.ImageField(null=True, upload_to='upload/avatars/')),
                ('text', tinymce.models.HTMLField(verbose_name='Текст')),
                ('date_edit', models.DateField()),
                ('tags', models.ManyToManyField(to='workshop.Tag', verbose_name='Тэги')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Резюме',
                'verbose_name_plural': 'Резюме',
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show', models.BooleanField(default=True, verbose_name='Показать')),
                ('text', tinymce.models.HTMLField(verbose_name='Текст')),
                ('date_edit', models.DateField(auto_now_add=True, verbose_name='Дата редактирования')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop.resume')),
            ],
            options={
                'verbose_name': 'Публикация',
                'verbose_name_plural': 'Публикации',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show', models.BooleanField(default=True, verbose_name='Показать')),
                ('icon', models.ImageField(null=True, upload_to='uploads/icons/', verbose_name='Иконка')),
                ('text', models.CharField(max_length=150, verbose_name='Текст')),
                ('url', models.URLField(verbose_name='URL')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop.publication')),
            ],
            options={
                'verbose_name': 'Ссылка',
                'verbose_name_plural': 'Ссылки',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show', models.BooleanField(default=True, verbose_name='Показать')),
                ('file', models.FileField(upload_to='uploads/files/')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop.publication')),
            ],
            options={
                'verbose_name': 'Вложение',
                'verbose_name_plural': 'Вложения',
            },
        ),
    ]
