# Generated by Django 3.2.13 on 2022-05-11 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show', models.BooleanField(default=True, verbose_name='Показать')),
                ('title', models.CharField(max_length=200, verbose_name='Загаловок')),
                ('order', models.IntegerField(verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Раздел',
                'verbose_name_plural': 'Разделы',
            },
        ),
        migrations.CreateModel(
            name='FileConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show', models.BooleanField(default=True, verbose_name='Показать')),
                ('text', tinymce.models.HTMLField(verbose_name='Настройки')),
            ],
            options={
                'verbose_name': 'Файл настройки',
                'verbose_name_plural': 'Файлы настройки',
            },
        ),
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show', models.BooleanField(default=True, verbose_name='Показать')),
                ('image', models.ImageField(null=True, upload_to='uploads/icons/', verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Иконка',
                'verbose_name_plural': 'Иконки',
            },
        ),
        migrations.CreateModel(
            name='TextInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show', models.BooleanField(default=True, verbose_name='Показать')),
                ('text', tinymce.models.HTMLField(verbose_name='Текст')),
                ('order', models.IntegerField(verbose_name='Порядок')),
                ('decorate', models.TextField(blank=True, verbose_name='Настройки отображения')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop.block')),
            ],
            options={
                'verbose_name': 'Описание',
                'verbose_name_plural': 'Описания',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show', models.BooleanField(default=True, verbose_name='Показать')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('icon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop.icon')),
            ],
            options={
                'verbose_name': 'Тэг',
                'verbose_name_plural': 'Тэги',
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show', models.BooleanField(default=True, verbose_name='Показать')),
                ('image', models.ImageField(null=True, upload_to='upload/avatars/')),
                ('text', tinymce.models.HTMLField(verbose_name='Текст')),
                ('date_edit', models.DateField()),
                ('tags', models.ManyToManyField(to='workshop.Tag', verbose_name='Тэги')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Резюме',
                'verbose_name_plural': 'Резюме',
            },
        ),
        migrations.CreateModel(
            name='FileInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show', models.BooleanField(default=True, verbose_name='Показать')),
                ('file', models.FileField(upload_to='uploads/files/')),
                ('description', models.CharField(max_length=200, verbose_name='Подпись')),
                ('order', models.IntegerField(verbose_name='Порядок')),
                ('decorate', models.TextField(blank=True, verbose_name='Настройки отображения')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop.block')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
            },
        ),
        migrations.AddField(
            model_name='block',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop.resume'),
        ),
    ]
