# Generated by Django 3.2.13 on 2022-05-09 07:48

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show', models.BooleanField(default=True, verbose_name='Показать')),
                ('title', models.CharField(max_length=200, verbose_name='Загаловок')),
                ('order', models.IntegerField(verbose_name='Порядок')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop.resume')),
            ],
            options={
                'verbose_name': 'Раздел',
                'verbose_name_plural': 'Разделы',
            },
        ),
        migrations.CreateModel(
            name='FileInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show', models.BooleanField(default=True, verbose_name='Показать')),
                ('file', models.FileField(upload_to='uploads/files/')),
                ('order', models.IntegerField(verbose_name='Порядок')),
                ('decorate', models.TextField(blank=True, verbose_name='Настройки отображения')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop.block')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
            },
        ),
        migrations.CreateModel(
            name='TextInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show', models.BooleanField(default=True, verbose_name='Показать')),
                ('text', tinymce.models.HTMLField(verbose_name='Текст')),
                ('order', models.IntegerField(verbose_name='Порядок')),
                ('decorate', models.TextField(blank=True, verbose_name='Настройки отображения')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop.block')),
            ],
            options={
                'verbose_name': 'Описание',
                'verbose_name_plural': 'Описания',
            },
        ),
        migrations.RemoveField(
            model_name='link',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='link',
            name='publication',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='resume',
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.DeleteModel(
            name='Link',
        ),
        migrations.DeleteModel(
            name='Publication',
        ),
    ]
