# Generated by Django 3.2.13 on 2022-05-02 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_skills_text'),
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fields',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='users.profile'),
        ),
        migrations.CreateModel(
            name='Publications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog', models.BooleanField(default=True)),
                ('text', models.TextField(verbose_name='Текст')),
                ('editDate', models.DateField(auto_now_add=True, verbose_name='Дата редактирования')),
                ('tags', models.ManyToManyField(related_name='tags', to='workshop.Tags', verbose_name='Тэги')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(null=True, upload_to='uploads/icons/', verbose_name='Иконка')),
                ('text', models.TextField(verbose_name='Текст')),
                ('url', models.CharField(max_length=150, verbose_name='URL')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_publication', to='workshop.publications')),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/files/')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publication', to='workshop.publications')),
            ],
        ),
    ]
