# Generated by Django 3.2.13 on 2022-05-11 19:07

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='date_edit',
            field=models.DateField(default=django.utils.datetime_safe.date.today, verbose_name='Дата последнего редактирования'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='date_edit',
            field=models.DateField(default=django.utils.datetime_safe.date.today, verbose_name='Дата последнего редактирования'),
        ),
    ]
