# Generated by Django 3.2.13 on 2022-05-03 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='show',
            field=models.BooleanField(default=True, verbose_name='Показать'),
        ),
        migrations.AddField(
            model_name='file',
            name='show',
            field=models.BooleanField(default=True, verbose_name='Показать'),
        ),
        migrations.AddField(
            model_name='link',
            name='show',
            field=models.BooleanField(default=True, verbose_name='Показать'),
        ),
        migrations.AddField(
            model_name='publication',
            name='show',
            field=models.BooleanField(default=True, verbose_name='Показать'),
        ),
        migrations.AddField(
            model_name='tag',
            name='show',
            field=models.BooleanField(default=True, verbose_name='Показать'),
        ),
    ]
