# Generated by Django 3.2.13 on 2022-05-11 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import workshop.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=1000, validators=[workshop.validators.OrReValidator(('[a-zA-Z0-9_]+@[a-zA-Z0-9_]+.[a-z0-9]+', '\\+?1?\\d{8,15}', 'https?://[a-zA-Z0-1]+.[a-zA-Z0-1]+(/[a-zA-Z0-1]+)*/?'))], verbose_name='Номер телефона | Email | URL')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
