# Generated by Django 3.2.13 on 2022-05-11 17:59

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', tinymce.models.HTMLField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Текст',
                'verbose_name_plural': 'Текста',
            },
        ),
        migrations.RenameModel(
            old_name='FileInfo',
            new_name='File',
        ),
        migrations.AlterModelOptions(
            name='block',
            options={'verbose_name': 'Блок', 'verbose_name_plural': 'Блоки'},
        ),
        migrations.AddField(
            model_name='resume',
            name='contacts',
            field=models.ManyToManyField(to='workshop.Contact', verbose_name='Контакты'),
        ),
        migrations.AlterField(
            model_name='block',
            name='order',
            field=models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='text',
            field=tinymce.models.HTMLField(verbose_name='Описание'),
        ),
        migrations.DeleteModel(
            name='TextInfo',
        ),
        migrations.AddField(
            model_name='text',
            name='block',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='workshop.block'),
        ),
    ]
