# Generated by Django 3.2.13 on 2022-05-09 07:50

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0002_auto_20220509_0748'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show', models.BooleanField(default=True, verbose_name='Показать')),
                ('text', tinymce.models.HTMLField(verbose_name='Настройки')),
            ],
            options={
                'verbose_name': 'Файл настройки',
                'verbose_name_plural': 'Файлы настройки',
            },
        ),
    ]
