# Generated by Django 3.2.13 on 2022-05-11 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0003_auto_20220511_2059'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileConfig',
        ),
        migrations.RemoveField(
            model_name='file',
            name='decorate',
        ),
        migrations.RemoveField(
            model_name='file',
            name='description',
        ),
        migrations.RemoveField(
            model_name='file',
            name='order',
        ),
    ]
