# Generated by Django 3.2.13 on 2022-05-25 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0003_auto_20220525_0259'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Icon',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='show',
        ),
    ]
