# Generated by Django 3.2.13 on 2022-05-25 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0005_auto_20220525_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/avatars/resume/'),
        ),
    ]
