# Generated by Django 3.2.13 on 2022-05-25 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0006_alter_resume_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='tags',
            field=models.ManyToManyField(blank=True, to='workshop.Tag', verbose_name='Теги'),
        ),
    ]
